import { jsPDF } from "jspdf";
import { UserProfile, GeneratedName, GeneratedSlogan, GeneratedLogo, GeneratedBrandKit, Language } from "../types";

// Helper to convert SVG string to Base64 PNG Data URL
export const svgToDataUrl = (svgStr: string): Promise<string> => {
  return new Promise((resolve) => {
    try {
      // Clean and standardise SVG string if needed
      const cleanedSvg = svgStr.trim();
      const svgBlob = new Blob([cleanedSvg], { type: 'image/svg+xml;charset=utf-8' });
      const url = URL.createObjectURL(svgBlob);
      const img = new Image();
      
      img.onload = () => {
        const canvas = document.createElement('canvas');
        // Good resolution for PDF embedding
        canvas.width = 400;
        canvas.height = 400;
        const ctx = canvas.getContext('2d');
        if (ctx) {
          ctx.fillStyle = '#ffffff';
          ctx.fillRect(0, 0, 400, 400);
          // Center and draw with some padding
          ctx.drawImage(img, 20, 20, 360, 360);
        }
        const dataUrl = canvas.toDataURL('image/png');
        URL.revokeObjectURL(url);
        resolve(dataUrl);
      };
      
      img.onerror = () => {
        URL.revokeObjectURL(url);
        resolve('');
      };
      
      img.src = url;
    } catch (e) {
      console.error("Error converting SVG to Data URL", e);
      resolve('');
    }
  });
};

// JSON Exporter
export const exportToJSON = (
  user: UserProfile,
  names: GeneratedName[],
  slogans: GeneratedSlogan[],
  logos: GeneratedLogo[],
  kits: GeneratedBrandKit[]
) => {
  const data = {
    exportDate: new Date().toISOString(),
    generator: "BrandForge AI",
    exportedBy: {
      name: user.displayName,
      email: user.email,
      plan: user.subscriptionPlan
    },
    brandingAssets: {
      brandNames: names.map(n => ({
        name: n.name,
        meaning: n.meaning,
        style: n.style,
        domainSuggestions: n.domainSuggestions,
        tags: n.tags || [],
        isFavorite: !!n.isFavorite
      })),
      slogans: slogans.map(s => ({
        slogan: s.slogan,
        vibe: s.vibe,
        tags: s.tags || [],
        isFavorite: !!s.isFavorite
      })),
      logos: logos.map(l => ({
        id: l.id,
        style: l.style,
        prompt: l.prompt,
        svg: l.svg,
        createdAt: l.createdAt,
        tags: l.tags || [],
        isFavorite: !!l.isFavorite
      })),
      brandKits: kits.map(k => ({
        id: k.id,
        name: k.name,
        slogan: k.slogan,
        colors: k.colors,
        typography: k.typography,
        socialKit: k.socialKit,
        logoSvg: k.logoSvg,
        createdAt: k.createdAt,
        tags: k.tags || [],
        isFavorite: !!k.isFavorite
      }))
    }
  };

  const jsonString = `data:text/json;charset=utf-8,${encodeURIComponent(
    JSON.stringify(data, null, 2)
  )}`;
  const downloadAnchor = document.createElement("a");
  downloadAnchor.setAttribute("href", jsonString);
  downloadAnchor.setAttribute("download", `brandforge-branding-report-${user.displayName.toLowerCase().replace(/\s+/g, '-')}.json`);
  document.body.appendChild(downloadAnchor);
  downloadAnchor.click();
  downloadAnchor.remove();
};

// PDF Report Exporter
export const exportToPDF = async (
  language: Language,
  user: UserProfile,
  names: GeneratedName[],
  slogans: GeneratedSlogan[],
  logos: GeneratedLogo[],
  kits: GeneratedBrandKit[]
) => {
  const isAr = language === 'ar';
  
  // Create jsPDF instance
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2); // 170mm

  let currentY = 25;

  // Helper to draw a clean line separator
  const drawSeparator = (y: number, color = [226, 232, 240]) => {
    doc.setDrawColor(color[0], color[1], color[2]);
    doc.setLineWidth(0.3);
    doc.line(margin, y, margin + contentWidth, y);
  };

  // Helper to add footer to pages
  const addFooter = (pageNum: number) => {
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // slate-400
    
    // Left side: BrandForge Info
    doc.text("Generated by BrandForge AI • Brand Identity Report", margin, pageHeight - 12);
    
    // Right side: Page Number
    const pageStr = `Page ${pageNum}`;
    doc.text(pageStr, pageWidth - margin - doc.getTextWidth(pageStr), pageHeight - 12);
    
    // Thin line above footer
    doc.setDrawColor(241, 245, 249);
    doc.setLineWidth(0.2);
    doc.line(margin, pageHeight - 16, margin + contentWidth, pageHeight - 16);
  };

  // Check if page overflow and create a new page if needed
  const checkPageOverflow = (heightNeeded: number): boolean => {
    if (currentY + heightNeeded > pageHeight - 25) {
      doc.addPage();
      currentY = 25;
      return true;
    }
    return false;
  };

  // ==========================================
  // PAGE 1: COVER PAGE
  // ==========================================
  
  // Background decorative accents
  doc.setFillColor(79, 70, 229, 0.05); // light indigo background
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  // Top accent bar
  doc.setFillColor(79, 70, 229); // Solid indigo
  doc.rect(0, 0, pageWidth, 15, "F");

  // Title Logo / Header
  currentY = 40;
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(28);
  doc.setTextColor(30, 41, 59); // slate-800
  doc.text("BrandForge AI", margin, currentY);

  currentY += 8;
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(14);
  doc.setTextColor(79, 70, 229); // Indigo
  doc.text(isAr ? "تقرير الهوية التجارية المتكامل" : "Comprehensive Brand Identity Report", margin, currentY);

  currentY += 25;
  drawSeparator(currentY, [79, 70, 229]);

  // Project Details Card
  currentY += 15;
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.roundedRect(margin, currentY, contentWidth, 75, 5, 5, "FD");

  // Inside Card Content
  let cardY = currentY + 12;
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(79, 70, 229);
  doc.text(isAr ? "تفاصيل التقرير" : "REPORT DETAILS", margin + 10, cardY);

  doc.setFont("Helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // slate-500
  
  cardY += 12;
  doc.text(isAr ? "المستلم:" : "PREPARED FOR:", margin + 10, cardY);
  doc.setFont("Helvetica", "normal");
  doc.setTextColor(30, 41, 59);
  doc.text(user.displayName, margin + 55, cardY);

  cardY += 10;
  doc.setFont("Helvetica", "bold");
  doc.setTextColor(100, 116, 139);
  doc.text(isAr ? "البريد الإلكتروني:" : "EMAIL ADDRESS:", margin + 10, cardY);
  doc.setFont("Helvetica", "normal");
  doc.setTextColor(30, 41, 59);
  doc.text(user.email, margin + 55, cardY);

  cardY += 10;
  doc.setFont("Helvetica", "bold");
  doc.setTextColor(100, 116, 139);
  doc.text(isAr ? "تاريخ الإصدار:" : "DATE GENERATED:", margin + 10, cardY);
  doc.setFont("Helvetica", "normal");
  doc.setTextColor(30, 41, 59);
  doc.text(new Date().toLocaleDateString(isAr ? 'ar-EG' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric' }), margin + 55, cardY);

  cardY += 10;
  doc.setFont("Helvetica", "bold");
  doc.setTextColor(100, 116, 139);
  doc.text(isAr ? "باقة الاشتراك:" : "SUBSCRIPTION PLAN:", margin + 10, cardY);
  doc.setFont("Helvetica", "bold");
  doc.setTextColor(79, 70, 229);
  doc.text(user.subscriptionPlan.toUpperCase(), margin + 55, cardY);

  currentY += 90;

  // Overview Summary Text
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(71, 85, 105); // slate-600
  
  const introText = isAr 
    ? "يحتوي هذا التقرير الفني على أصول الهوية البصرية واللفظية التي تم إنشاؤها وتنسيقها بعناية باستخدام الذكاء الاصطناعي المتقدم في BrandForge. يشمل التقرير الأسماء المقترحة، الشعارات اللفظية، تصاميم الهوية البصرية، والكتيبات التوجيهية للعلامة التجارية لضمان توافق رؤيتك التجارية وتأثيرها في السوق."
    : "This tailored design dossier contains your curated brand assets generated using BrandForge AI. It details selected brand names, slogans, high-fidelity logos, and unified brand style guides to help establish a distinct market position and unified brand voice.";
  
  const splitIntro = doc.splitTextToSize(introText, contentWidth - 10);
  doc.text(splitIntro, margin + 5, currentY);

  // Footer on cover
  addFooter(1);

  // ==========================================
  // PAGE 2: BRAND NAMES
  // ==========================================
  doc.addPage();
  currentY = 25;
  addFooter(2);
  let pageNum = 2;

  // Page Header
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(30, 41, 59);
  doc.text(isAr ? "1. الأسماء التجارية المبتكرة" : "1. Curated Brand Names", margin, currentY);
  currentY += 5;
  drawSeparator(currentY);
  currentY += 10;

  if (names.length === 0) {
    doc.setFont("Helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184);
    doc.text(isAr ? "لا توجد أسماء تجارية محفوظة حتى الآن." : "No saved brand names found in your workspace.", margin, currentY);
    currentY += 15;
  } else {
    for (let i = 0; i < names.length; i++) {
      const item = names[i];
      
      // Check for page overflow
      if (checkPageOverflow(50)) {
        pageNum++;
        addFooter(pageNum);
        
        // Re-draw small header on new page for context
        doc.setFont("Helvetica", "bold");
        doc.setFontSize(10);
        doc.setTextColor(148, 163, 184);
        doc.text(isAr ? "الأسماء التجارية (تابع)" : "Brand Names (Continued)", margin, currentY);
        currentY += 4;
        drawSeparator(currentY);
        currentY += 8;
      }

      // Name container block
      doc.setFillColor(255, 255, 255);
      doc.setDrawColor(241, 245, 249);
      doc.setLineWidth(0.3);
      doc.roundedRect(margin, currentY, contentWidth, 38, 3, 3, "FD");

      // Name title
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(14);
      doc.setTextColor(79, 70, 229); // Brand primary
      doc.text(item.name, margin + 8, currentY + 8);

      // Style badge
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      const styleLabel = `${isAr ? "الأسلوب:" : "STYLE:"} ${item.style.toUpperCase()}`;
      doc.text(styleLabel, margin + contentWidth - doc.getTextWidth(styleLabel) - 8, currentY + 8);

      // Meaning / Concept
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(30, 41, 59);
      doc.text(isAr ? "المفهوم والدلالة:" : "CONCEPT & MEANING:", margin + 8, currentY + 16);

      doc.setFont("Helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(71, 85, 105);
      
      const meaningText = (isAr && item.meaningAr) ? item.meaningAr : item.meaning;
      const splitMeaning = doc.splitTextToSize(meaningText, contentWidth - 20);
      doc.text(splitMeaning, margin + 8, currentY + 21);

      // Domain Suggestion
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      const domainLabel = `${isAr ? "النطاق المقترح:" : "DOMAIN RECOMMENDATION:"} ${item.domainSuggestions?.[0] || `${item.name.toLowerCase().replace(/\s+/g, '')}.com`}`;
      doc.text(domainLabel, margin + 8, currentY + 32);

      currentY += 45;
    }
  }

  // ==========================================
  // PAGE 3: BRAND SLOGANS
  // ==========================================
  if (checkPageOverflow(60)) {
    pageNum++;
    addFooter(pageNum);
  } else {
    doc.addPage();
    pageNum++;
    addFooter(pageNum);
    currentY = 25;
  }

  doc.setFont("Helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(30, 41, 59);
  doc.text(isAr ? "2. الشعارات اللفظية والهوية الكلامية" : "2. Dynamic Brand Slogans", margin, currentY);
  currentY += 5;
  drawSeparator(currentY);
  currentY += 10;

  if (slogans.length === 0) {
    doc.setFont("Helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184);
    doc.text(isAr ? "لا توجد شعارات لفظية محفوظة حتى الآن." : "No saved slogans found in your workspace.", margin, currentY);
    currentY += 15;
  } else {
    for (let i = 0; i < slogans.length; i++) {
      const item = slogans[i];

      if (checkPageOverflow(28)) {
        pageNum++;
        addFooter(pageNum);
        doc.setFont("Helvetica", "bold");
        doc.setFontSize(10);
        doc.setTextColor(148, 163, 184);
        doc.text(isAr ? "الشعارات اللفظية (تابع)" : "Slogans (Continued)", margin, currentY);
        currentY += 4;
        drawSeparator(currentY);
        currentY += 8;
      }

      // Slogan Block
      doc.setFillColor(255, 255, 255);
      doc.setDrawColor(241, 245, 249);
      doc.setLineWidth(0.3);
      doc.roundedRect(margin, currentY, contentWidth, 20, 3, 3, "FD");

      // Quote / Slogan
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(30, 41, 59);
      doc.text(`"${item.slogan}"`, margin + 8, currentY + 8);

      // Vibe Label
      doc.setFont("Helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(79, 70, 229);
      doc.text(`${isAr ? "نبرة الصوت:" : "BRAND VIBE:"} ${item.vibe.toUpperCase()}`, margin + 8, currentY + 15);

      currentY += 26;
    }
  }

  // ==========================================
  // PAGE 4: LOGOS (WITH HIGH-FIDELITY IMAGES)
  // ==========================================
  if (checkPageOverflow(80)) {
    pageNum++;
    addFooter(pageNum);
  } else {
    doc.addPage();
    pageNum++;
    addFooter(pageNum);
    currentY = 25;
  }

  doc.setFont("Helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(30, 41, 59);
  doc.text(isAr ? "3. الشعارات والهويات البصرية" : "3. Visual Logos & Marks", margin, currentY);
  currentY += 5;
  drawSeparator(currentY);
  currentY += 10;

  if (logos.length === 0) {
    doc.setFont("Helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184);
    doc.text(isAr ? "لا توجد تصاميم شعارات محفوظة حتى الآن." : "No saved brand logos found in your workspace.", margin, currentY);
    currentY += 15;
  } else {
    for (let i = 0; i < logos.length; i++) {
      const item = logos[i];

      // Check overflow (logos take more space because we render them)
      if (checkPageOverflow(75)) {
        pageNum++;
        addFooter(pageNum);
        doc.setFont("Helvetica", "bold");
        doc.setFontSize(10);
        doc.setTextColor(148, 163, 184);
        doc.text(isAr ? "الشعارات البصرية (تابع)" : "Visual Logos (Continued)", margin, currentY);
        currentY += 4;
        drawSeparator(currentY);
        currentY += 8;
      }

      // Container rounded rect
      doc.setFillColor(255, 255, 255);
      doc.setDrawColor(241, 245, 249);
      doc.setLineWidth(0.3);
      doc.roundedRect(margin, currentY, contentWidth, 65, 4, 4, "FD");

      // Draw vector placeholder or actual SVG convert on canvas
      let imageAdded = false;
      if (item.svg) {
        try {
          const imgDataUrl = await svgToDataUrl(item.svg);
          if (imgDataUrl) {
            // Embed high-fidelity SVG render
            doc.addImage(imgDataUrl, "PNG", margin + 6, currentY + 7, 50, 50);
            imageAdded = true;
          }
        } catch (err) {
          console.error("Could not render logo in PDF", err);
        }
      }

      const textXOffset = imageAdded ? 64 : 12;

      // Logo Info
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(79, 70, 229);
      doc.text(`${isAr ? "شعار:" : "LOGO STYLE:"} ${item.style.toUpperCase()}`, margin + textXOffset, currentY + 14);

      doc.setFont("Helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(100, 116, 139);
      doc.text(isAr ? "التوجيه الإبداعي / الوصف:" : "CREATIVE DIRECTION / PROMPT:", margin + textXOffset, currentY + 22);

      doc.setFont("Helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(71, 85, 105);
      const promptText = item.prompt;
      const splitPrompt = doc.splitTextToSize(promptText, contentWidth - textXOffset - 8);
      doc.text(splitPrompt, margin + textXOffset, currentY + 27);

      // Unique Identifier
      doc.setFont("Helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(148, 163, 184);
      doc.text(`Asset ID: ${item.id}`, margin + textXOffset, currentY + 58);

      currentY += 72;
    }
  }

  // ==========================================
  // PAGE 5: BRAND KITS & STYLES
  // ==========================================
  if (kits.length > 0) {
    if (checkPageOverflow(80)) {
      pageNum++;
      addFooter(pageNum);
    } else {
      doc.addPage();
      pageNum++;
      addFooter(pageNum);
      currentY = 25;
    }

    doc.setFont("Helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(30, 41, 59);
    doc.text(isAr ? "4. الهوية البصرية المتكاملة والدليل" : "4. Integrated Brand Books", margin, currentY);
    currentY += 5;
    drawSeparator(currentY);
    currentY += 10;

    for (let i = 0; i < kits.length; i++) {
      const kit = kits[i];

      if (checkPageOverflow(100)) {
        pageNum++;
        addFooter(pageNum);
        doc.setFont("Helvetica", "bold");
        doc.setFontSize(10);
        doc.setTextColor(148, 163, 184);
        doc.text(isAr ? "دليل الهوية المتكاملة (تابع)" : "Integrated Brand Books (Continued)", margin, currentY);
        currentY += 4;
        drawSeparator(currentY);
        currentY += 8;
      }

      // Brand Kit Box
      doc.setFillColor(255, 255, 255);
      doc.setDrawColor(241, 245, 249);
      doc.setLineWidth(0.3);
      doc.roundedRect(margin, currentY, contentWidth, 92, 4, 4, "FD");

      // Brand Kit Title
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(13);
      doc.setTextColor(30, 41, 59);
      doc.text(kit.name, margin + 8, currentY + 10);

      // Slogan
      doc.setFont("Helvetica", "italic");
      doc.setFontSize(9.5);
      doc.setTextColor(79, 70, 229);
      doc.text(`"${kit.slogan || ''}"`, margin + 8, currentY + 16);

      // Colors Header
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(100, 116, 139);
      doc.text(isAr ? "لوحة الألوان الأساسية:" : "BRAND COLOR PALETTE:", margin + 8, currentY + 26);

      // Color Swatches
      const colors = [
        { label: "Primary", val: kit.colors.primary },
        { label: "Secondary", val: kit.colors.secondary },
        { label: "Accent", val: kit.colors.accent },
        { label: "Background", val: kit.colors.background },
        { label: "Text", val: kit.colors.text }
      ];

      let swatchX = margin + 8;
      for (let c = 0; c < colors.length; c++) {
        const col = colors[c];
        
        // Swatch rect
        doc.setFillColor(col.val);
        doc.setDrawColor(226, 232, 240);
        doc.setLineWidth(0.2);
        doc.roundedRect(swatchX, currentY + 29, 28, 12, 1, 1, "FD");

        // Color Hex Label inside or below
        doc.setFont("Helvetica", "bold");
        doc.setFontSize(7);
        doc.setTextColor(100, 116, 139);
        doc.text(col.val, swatchX, currentY + 45);

        doc.setFont("Helvetica", "normal");
        doc.setFontSize(6.5);
        doc.text(col.label, swatchX, currentY + 49);

        swatchX += 32;
      }

      // Typography
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(100, 116, 139);
      doc.text(isAr ? "الخطوط والأنماط:" : "BRAND TYPOGRAPHY STYLE:", margin + 8, currentY + 57);

      doc.setFont("Helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(30, 41, 59);
      doc.text(`${isAr ? "العناوين:" : "Heading:"} ${kit.typography.heading}`, margin + 8, currentY + 63);
      doc.text(`${isAr ? "النصوص:" : "Body:"} ${kit.typography.body}`, margin + 84, currentY + 63);

      doc.setFont("Helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(71, 85, 105);
      const typographyRationale = kit.typography.rationale || "";
      const splitRationale = doc.splitTextToSize(typographyRationale, contentWidth - 16);
      doc.text(splitRationale, margin + 8, currentY + 69);

      // Social Kit Bio
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      doc.text(isAr ? "السيرة الذاتية المقترحة للمنصات:" : "PROPOSED SOCIAL BIO:", margin + 8, currentY + 81);

      doc.setFont("Helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(71, 85, 105);
      doc.text(kit.socialKit.bio || "", margin + 8, currentY + 86);

      currentY += 100;
    }
  }

  // Save the PDF
  const filename = `brandforge-branding-report-${user.displayName.toLowerCase().replace(/\s+/g, '-')}.pdf`;
  doc.save(filename);
};
