import re

with open('server.ts', 'r') as f:
    content = f.read()

# Replace JSON.parse(cleanJSON(text)) with safe parse
safe_parse = """
    let data;
    try {
      data = JSON.parse(cleanJSON(text));
    } catch (e) {
      console.error("JSON Parse Error. Raw text:", text.substring(0, 500) + "...");
      throw new Error("Invalid JSON generated by AI.");
    }
"""

content = re.sub(r'const data = JSON\.parse\(cleanJSON\(text\)\);', safe_parse.strip(), content)

with open('server.ts', 'w') as f:
    f.write(content)
