import re

with open('src/components/BrandKitGenerator.tsx', 'r') as f:
    content = f.read()

# Add Share2 to imports if not already there
if "Share2" not in content:
    content = content.replace("RefreshCw } from 'lucide-react'", "RefreshCw, Share2 } from 'lucide-react'")

# Add handleShare method
handle_share_method = """  const handleShare = async () => {
    if (!kitResult) return;
    const textToShare = `Brand Kit for ${kitResult.name}: ${kitResult.slogan}\\nColors: ${Object.values(kitResult.colors).join(', ')}\\nGenerated by BrandForge AI`;
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Brand Kit',
          text: textToShare,
        });
      } catch (err) {
        console.error('Error sharing:', err);
      }
    } else {
      navigator.clipboard.writeText(textToShare);
      alert(language === 'ar' ? 'تم نسخ النص للمشاركة!' : 'Text copied to clipboard for sharing!');
    }
  };

  const handleSaveKit"""
if "const handleShare" not in content:
    content = content.replace("  const handleSaveKit", handle_share_method)

# Add share button to UI
share_btn = """              <button
                onClick={handleShare}
                className="flex items-center gap-2 px-4 py-2 bg-blue-50 hover:bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:hover:bg-blue-900/50 dark:text-blue-400 rounded-xl text-xs font-semibold transition cursor-pointer"
              >
                <Share2 className="w-3.5 h-3.5" />
                <span>{language === 'ar' ? 'مشاركة' : 'Share'}</span>
              </button>
              <button
                onClick={exportToPDF}"""
content = content.replace("""              <button
                onClick={exportToPDF}""", share_btn)

with open('src/components/BrandKitGenerator.tsx', 'w') as f:
    f.write(content)
