import re

with open('src/components/NameGenerator.tsx', 'r') as f:
    content = f.read()

# Add Share2 to imports
content = content.replace("AlertTriangle, HelpCircle } from 'lucide-react'", "AlertTriangle, HelpCircle, Share2 } from 'lucide-react'")

# Add handleShare method
handle_share_method = """  const handleShare = async (item: GeneratedName) => {
    const textToShare = `${item.name} - ${brandLang === 'ar' && item.meaningAr ? item.meaningAr : item.meaning}\\nGenerated by BrandForge AI`;
    if (navigator.share) {
      try {
        await navigator.share({
          title: item.name,
          text: textToShare,
        });
      } catch (err) {
        console.error('Error sharing:', err);
      }
    } else {
      navigator.clipboard.writeText(textToShare);
      alert(language === 'ar' ? 'تم نسخ النص للمشاركة!' : 'Text copied to clipboard for sharing!');
    }
  };

  const handleCopy"""
content = content.replace("  const handleCopy", handle_share_method)

# Add share button to UI
share_btn = """                      </button>
                      <button
                        onClick={() => handleShare(item)}
                        className="p-1.5 hover:bg-slate-50 dark:hover:bg-slate-800 rounded-lg text-slate-400 hover:text-blue-500 transition cursor-pointer"
                        title={language === 'ar' ? 'مشاركة' : 'Share'}
                      >
                        <Share2 className="w-4 h-4" />
                      </button>
                      <button"""
content = content.replace("                      </button>\n                      <button\n                        onClick={() => onSaveName(item)}", share_btn + "\n                        onClick={() => onSaveName(item)}")

with open('src/components/NameGenerator.tsx', 'w') as f:
    f.write(content)
