import re

with open('src/components/LogoGenerator.tsx', 'r') as f:
    content = f.read()

# Add Share2 to imports
content = content.replace("Maximize2 } from 'lucide-react'", "Maximize2, Share2 } from 'lucide-react'")

# Add handleShare method
handle_share_method = """  const handleShare = async () => {
    if (!logoResult) return;
    const textToShare = `Logo Concept: ${prompt} (${selectedStyle})\\nGenerated by BrandForge AI`;
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Brand Logo Concept',
          text: textToShare,
        });
      } catch (err) {
        console.error('Error sharing:', err);
      }
    } else {
      navigator.clipboard.writeText(textToShare);
      alert(language === 'ar' ? 'تم نسخ النص للمشاركة!' : 'Text copied to clipboard for sharing!');
    }
  };

  const handleCopySVG"""
content = content.replace("  const handleCopySVG", handle_share_method)

# Add share button to UI
share_btn = """                  <button
                    onClick={() => handleDownloadPNG(true)}
                    className="flex items-center justify-center gap-2 border border-slate-200 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-800 text-slate-600 dark:text-slate-300 text-sm font-semibold py-3 rounded-xl transition cursor-pointer"
                  >
                    <FileCode className="w-4 h-4 text-emerald-500" />
                    <span>{t.downloadPngTrans}</span>
                  </button>
                  <button
                    onClick={handleShare}
                    className="col-span-2 flex items-center justify-center gap-2 border border-blue-200 dark:border-blue-900 bg-blue-50/50 hover:bg-blue-50 dark:bg-blue-950/20 dark:hover:bg-blue-950/40 text-blue-600 dark:text-blue-400 text-sm font-semibold py-3 rounded-xl transition cursor-pointer"
                  >
                    <Share2 className="w-4 h-4" />
                    <span>{language === 'ar' ? 'مشاركة الفكرة' : 'Share Idea'}</span>
                  </button>"""
content = content.replace("""                  <button
                    onClick={() => handleDownloadPNG(true)}
                    className="flex items-center justify-center gap-2 border border-slate-200 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-800 text-slate-600 dark:text-slate-300 text-sm font-semibold py-3 rounded-xl transition cursor-pointer"
                  >
                    <FileCode className="w-4 h-4 text-emerald-500" />
                    <span>{t.downloadPngTrans}</span>
                  </button>""", share_btn)

with open('src/components/LogoGenerator.tsx', 'w') as f:
    f.write(content)
