import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import React, { useState } from 'react';
import { translations } from '../translations';
import { Language, UserProfile, GeneratedBrandKit } from '../types';
import { Download, Sparkles, Bookmark, Copy, Check, Palette, Type, MessageSquare, AlertTriangle, RefreshCw, Share2 } from 'lucide-react';
import { fetchAPI } from '../lib/api';

interface BrandKitGeneratorProps {
  language: Language;
  user: UserProfile | null;
  onDeductCredits: (amount: number) => boolean;
  onSaveBrandKit: (kit: GeneratedBrandKit) => void;
  savedKits: GeneratedBrandKit[];
  onOpenLogin: () => void;
}

export default function BrandKitGenerator({
  language,
  user,
  onDeductCredits,
  onSaveBrandKit,
  savedKits,
  onOpenLogin,
}: BrandKitGeneratorProps) {
  const t = translations[language];

  const [name, setName] = useState('');
  const [prompt, setPrompt] = useState('');
  const [brandLang, setBrandLang] = useState(language);
  const [loading, setLoading] = useState(false);
  const [kitResult, setKitResult] = useState<GeneratedBrandKit | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copiedSection, setCopiedSection] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);

  const handleGenerate = async () => {
    if (!name.trim() || !prompt.trim()) return;

    if (!user) {
      onOpenLogin();
      return;
    }

    setError(null);
    setLoading(true);
    setKitResult(null);
    setSaved(false);

    // Cost: 4 credits
    const success = onDeductCredits(4);
    if (!success) {
      setError(language === 'en' ? 'Insufficient credits! Please upgrade your plan or purchase credits.' : 'رصيدك غير كافٍ! يرجى ترقية باقتك أو شراء رصيد إضافي.');
      setLoading(false);
      return;
    }

    try {
      const resJson = await fetchAPI('/api/generate-brand-kit', {
        method: 'POST',
        body: JSON.stringify({
          name,
          prompt,
          language: brandLang
        })
      });

      if (resJson.success) {
        setKitResult({
          ...resJson.data,
          id: `kit-${Date.now()}`,
          name,
          slogan: '',
          createdAt: new Date().toISOString()
        });
      } else {
        throw new Error(resJson.error || 'Failed to generate brand kit');
      }
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Something went wrong. Please check your internet connection and try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleCopyText = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(key);
    setTimeout(() => setCopiedSection(null), 2000);
  };

  const handleShare = async () => {
    if (!kitResult) return;
    const textToShare = `Brand Kit for ${kitResult.name}: ${kitResult.slogan}\nColors: ${Object.values(kitResult.colors).join(', ')}\nGenerated by BrandForge AI`;
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Brand Kit',
          text: textToShare,
        });
      } catch (err) {
        console.error('Error sharing:', err);
      }
    } else {
      navigator.clipboard.writeText(textToShare);
      alert(language === 'ar' ? 'تم نسخ النص للمشاركة!' : 'Text copied to clipboard for sharing!');
    }
  };

  const handleSaveKit = () => {
    if (!kitResult) return;
    onSaveBrandKit(kitResult);
    setSaved(true);
  };

  const exportToPDF = async () => {
    const element = document.getElementById('brand-kit-content');
    if (!element) return;
    try {
      const canvas = await html2canvas(element, { scale: 2, useCORS: true });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      pdf.save(`${kitResult?.name || 'brand'}-kit.pdf`);
    } catch (err) {
      console.error("PDF export failed", err);
    }
  };

  return (
    <div className="space-y-8 animate-fade-in">
      <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl p-6 sm:p-8 shadow-xl shadow-slate-100/40 dark:shadow-none">
        
        <div className="flex items-center gap-3 mb-6">
          <div className="bg-indigo-100 dark:bg-indigo-950/50 p-2.5 rounded-2xl text-indigo-600 dark:text-indigo-400">
            <Palette className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-display font-bold text-slate-900 dark:text-white">
              {t.brandKit}
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              Generates a holistic brand identity: custom color archetype swatches, font pairings, and social media media guidelines (Costs 4 credits)
            </p>
          </div>
        </div>

        {/* Configurations */}
        <div className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="md:col-span-2">
              <label className="block text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2">
                Brand Name
              </label>
              <input
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="e.g. EcoKicks, Solara, Vertex AI"
                className="w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-white focus:border-indigo-500 focus:outline-none transition-all"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2">
                {t.language}
              </label>
              <select
                value={brandLang}
                onChange={(e) => setBrandLang(e.target.value as Language)}
                className="w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 text-slate-700 dark:text-slate-300 focus:border-indigo-500 focus:outline-none transition-all"
              >
                <option value="en">{t.english}</option>
                <option value="ar">{t.arabic}</option>
              </select>
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2">
              Brand Values, Aesthetics, and Ethos
            </label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g. Modern, high-end organic tech brand. Minimalist style, targetting Gen-Z. Promotes circular economy."
              rows={3}
              className="w-full px-4 py-3 text-sm rounded-2xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 dark:focus:ring-indigo-950/40 focus:outline-none transition-all placeholder:text-slate-400"
            />
          </div>

          {/* Prompt cost & button */}
          <div className="flex items-center justify-between pt-4 border-t border-slate-100 dark:border-slate-800">
            <div className="flex items-center gap-2 text-xs text-slate-500 dark:text-slate-400">
              <span className="inline-block w-2 h-2 rounded-full bg-amber-500 animate-pulse"></span>
              <span>Credits Cost: 4 credits</span>
            </div>

            <button
              onClick={handleGenerate}
              disabled={loading || !name.trim() || !prompt.trim()}
              className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white font-medium text-sm px-6 py-3 rounded-xl transition duration-150 cursor-pointer shadow-lg shadow-indigo-600/10"
            >
              {loading ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" />
                  <span>{t.generating}</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  <span>{t.generate}</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* Error Alert */}
      {error && (
        <div className="flex items-start gap-3 p-4 rounded-2xl bg-rose-50 dark:bg-rose-950/20 border border-rose-100 dark:border-rose-900 text-rose-800 dark:text-rose-400 text-sm">
          <AlertTriangle className="w-5 h-5 flex-shrink-0 mt-0.5" />
          <p>{error}</p>
        </div>
      )}

      {/* Loading Skeletons */}
      {loading && (
        <div className="space-y-6 animate-pulse">
          
          <div className="flex items-center justify-between">
            <div className="h-6 w-48 bg-slate-200 dark:bg-slate-800 rounded-lg"></div>
            <div className="h-8 w-24 bg-slate-100 dark:bg-slate-800 rounded-xl"></div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            
            {/* 1. Color Palette Card Skeleton */}
            <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl p-6 shadow-md space-y-6">
              <div className="flex items-center gap-2 pb-3 border-b border-slate-100 dark:border-slate-800">
                <div className="w-5 h-5 bg-slate-200 dark:bg-slate-700 rounded-full"></div>
                <div className="w-24 h-5 bg-slate-200 dark:bg-slate-800 rounded-lg"></div>
              </div>

              <div>
                <div className="w-20 h-3 bg-slate-150 dark:bg-slate-850 rounded mb-1.5"></div>
                <div className="w-32 h-4 bg-slate-200 dark:bg-slate-800 rounded"></div>
              </div>

              {/* Swatches Grid Skeleton */}
              <div className="space-y-3">
                {[...Array(5)].map((_, idx) => (
                  <div key={idx} className="flex items-center justify-between p-2.5 rounded-xl border border-slate-100 dark:border-slate-850 bg-slate-50/50 dark:bg-slate-950/40">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-lg bg-slate-200 dark:bg-slate-800" />
                      <div className="space-y-1.5">
                        <div className="w-24 h-4 bg-slate-150 dark:bg-slate-850 rounded" />
                        <div className="w-12 h-3 bg-slate-100 dark:bg-slate-900 rounded font-mono" />
                      </div>
                    </div>
                    <div className="w-7 h-7 bg-slate-100 dark:bg-slate-850 rounded-lg"></div>
                  </div>
                ))}
              </div>
            </div>

            {/* 2. Typography Card Skeleton */}
            <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl p-6 shadow-md space-y-6 flex flex-col justify-between">
              <div>
                <div className="flex items-center gap-2 pb-3 border-b border-slate-100 dark:border-slate-800 mb-6">
                  <div className="w-5 h-5 bg-slate-200 dark:bg-slate-700 rounded-full"></div>
                  <div className="w-24 h-5 bg-slate-200 dark:bg-slate-800 rounded-lg"></div>
                </div>

                <div className="space-y-6">
                  <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-950 border border-slate-100 dark:border-slate-850 space-y-2">
                    <div className="w-20 h-3 bg-slate-200 dark:bg-slate-800 rounded"></div>
                    <div className="w-40 h-6 bg-slate-200 dark:bg-slate-700 rounded"></div>
                    <div className="w-48 h-3 bg-slate-100 dark:bg-slate-900 rounded"></div>
                  </div>

                  <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-950 border border-slate-100 dark:border-slate-850 space-y-2">
                    <div className="w-20 h-3 bg-slate-200 dark:bg-slate-800 rounded"></div>
                    <div className="w-32 h-5 bg-slate-200 dark:bg-slate-700 rounded"></div>
                    <div className="w-48 h-3 bg-slate-100 dark:bg-slate-900 rounded"></div>
                  </div>

                  <div className="pt-2 space-y-2">
                    <div className="w-32 h-3 bg-slate-200 dark:bg-slate-800 rounded"></div>
                    <div className="w-full h-4 bg-slate-100 dark:bg-slate-850 rounded"></div>
                    <div className="w-5/6 h-4 bg-slate-100 dark:bg-slate-850 rounded"></div>
                  </div>
                </div>
              </div>
            </div>

            {/* 3. Social Branding Suite Skeleton */}
            <div className="md:col-span-2 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl p-6 sm:p-8 shadow-md space-y-6">
              <div className="flex items-center gap-2 pb-3 border-b border-slate-100 dark:border-slate-800">
                <div className="w-5 h-5 bg-slate-200 dark:bg-slate-700 rounded-full"></div>
                <div className="w-48 h-5 bg-slate-200 dark:bg-slate-800 rounded-lg"></div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <div className="w-36 h-3 bg-slate-200 dark:bg-slate-800 rounded"></div>
                    <div className="w-7 h-7 bg-slate-100 dark:bg-slate-850 rounded-lg"></div>
                  </div>
                  <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-950 border border-slate-100 dark:border-slate-850 space-y-2">
                    <div className="w-full h-4 bg-slate-100 dark:bg-slate-850 rounded flex flex-col gap-1"></div>
                    <div className="w-full h-4 bg-slate-100 dark:bg-slate-850 rounded flex flex-col gap-1"></div>
                    <div className="w-3/4 h-4 bg-slate-100 dark:bg-slate-850 rounded flex flex-col gap-1"></div>
                  </div>
                </div>

                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <div className="w-36 h-3 bg-slate-200 dark:bg-slate-800 rounded"></div>
                    <div className="w-7 h-7 bg-slate-100 dark:bg-slate-850 rounded-lg"></div>
                  </div>
                  <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-950 border border-slate-100 dark:border-slate-850 space-y-2">
                    <div className="w-full h-4 bg-slate-100 dark:bg-slate-850 rounded flex flex-col gap-1"></div>
                    <div className="w-full h-4 bg-slate-100 dark:bg-slate-850 rounded flex flex-col gap-1"></div>
                    <div className="w-3/4 h-4 bg-slate-100 dark:bg-slate-850 rounded flex flex-col gap-1"></div>
                  </div>
                </div>

                <div className="md:col-span-2 space-y-3">
                  <div className="flex items-center justify-between">
                    <div className="w-64 h-3 bg-slate-200 dark:bg-slate-800 rounded"></div>
                    <div className="w-7 h-7 bg-slate-100 dark:bg-slate-850 rounded-lg"></div>
                  </div>
                  <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-950 border border-slate-100 dark:border-slate-850 space-y-2">
                    <div className="w-full h-4 bg-slate-100 dark:bg-slate-850 rounded"></div>
                    <div className="w-full h-4 bg-slate-100 dark:bg-slate-850 rounded"></div>
                    <div className="w-full h-4 bg-slate-100 dark:bg-slate-850 rounded"></div>
                    <div className="w-1/2 h-4 bg-slate-100 dark:bg-slate-850 rounded"></div>
                  </div>
                </div>

              </div>
            </div>

          </div>
        </div>
      )}

      {/* Results Display */}
      {kitResult && !loading && (
        <div id="brand-kit-content" className="space-y-6 animate-fade-in bg-slate-50 dark:bg-slate-950 p-6 rounded-3xl">
          
          <div className="flex items-center justify-between" data-html2canvas-ignore="true">
            <h3 className="font-display font-semibold text-lg text-slate-800 dark:text-slate-200">
              Forged Brand Kit Definition
            </h3>
            <div className="flex items-center gap-2">
              <button
                onClick={handleShare}
                className="flex items-center gap-2 px-4 py-2 bg-blue-50 hover:bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:hover:bg-blue-900/50 dark:text-blue-400 rounded-xl text-xs font-semibold transition cursor-pointer"
              >
                <Share2 className="w-3.5 h-3.5" />
                <span>{language === 'ar' ? 'مشاركة' : 'Share'}</span>
              </button>
              <button
                onClick={exportToPDF}
                className="flex items-center gap-2 px-4 py-2 bg-indigo-50 hover:bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:hover:bg-indigo-900/50 dark:text-indigo-400 rounded-xl text-xs font-semibold transition cursor-pointer"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Export PDF</span>
              </button>
              <button
                onClick={handleSaveKit}
                disabled={saved}
                className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold transition cursor-pointer ${
                  saved 
                    ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/20 dark:text-emerald-400' 
                    : 'bg-amber-500 hover:bg-amber-600 text-white shadow-md'
                }`}
              >
                <Bookmark className="w-3.5 h-3.5" />
                <span>{saved ? t.saved : t.save}</span>
              </button>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            
            {/* 1. Color Palette Card */}
            <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl p-6 shadow-md space-y-6">
              <div className="flex items-center gap-2 pb-3 border-b border-slate-100 dark:border-slate-800">
                <Palette className="w-5 h-5 text-indigo-500" />
                <h4 className="font-display font-bold text-slate-900 dark:text-white text-base">
                  {t.colors}
                </h4>
              </div>

              {/* Archetype Label */}
              <div>
                <span className="text-[10px] text-slate-400 uppercase font-bold tracking-widest block">Palette Theme</span>
                <span className="text-sm font-semibold text-slate-700 dark:text-slate-300">
                  Modern Minimalist
                </span>
              </div>

              {/* Swatches Grid */}
              <div className="space-y-3">
                {[
                  { name: 'Primary Core', hex: kitResult.colors.primary },
                  { name: 'Secondary Base', hex: kitResult.colors.secondary },
                  { name: 'Accent Highlight', hex: kitResult.colors.accent },
                  { name: 'Background Canvas', hex: kitResult.colors.background },
                  { name: 'Contrast Text', hex: kitResult.colors.text }
                ].map((item, idx) => (
                  <div key={idx} className="flex items-center justify-between p-2.5 rounded-xl border border-slate-100 dark:border-slate-850 bg-slate-50/50 dark:bg-slate-950/40">
                    <div className="flex items-center gap-3">
                      <div 
                        className="w-10 h-10 rounded-lg shadow-md border border-slate-200/50 dark:border-slate-800"
                        style={{ backgroundColor: item.hex }}
                      />
                      <div>
                        <span className="block text-xs font-semibold text-slate-800 dark:text-slate-200">{item.name}</span>
                        <span className="font-mono text-[10px] text-slate-400">{item.hex}</span>
                      </div>
                    </div>

                    <button
                      onClick={() => handleCopyText(item.hex, `hex-${idx}`)}
                      className="p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-400 hover:text-indigo-600 transition cursor-pointer"
                    >
                      {copiedSection === `hex-${idx}` ? (
                        <Check className="w-3.5 h-3.5 text-emerald-500" />
                      ) : (
                        <Copy className="w-3.5 h-3.5" />
                      )}
                    </button>
                  </div>
                ))}
              </div>
            </div>

            {/* 2. Typography Card */}
            <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl p-6 shadow-md space-y-6 flex flex-col justify-between">
              <div>
                <div className="flex items-center gap-2 pb-3 border-b border-slate-100 dark:border-slate-800 mb-6">
                  <Type className="w-5 h-5 text-indigo-500" />
                  <h4 className="font-display font-bold text-slate-900 dark:text-white text-base">
                    {t.typography}
                  </h4>
                </div>

                <div className="space-y-6">
                  {/* Heading typography */}
                  <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-950 border border-slate-100 dark:border-slate-850">
                    <span className="text-[10px] font-bold text-indigo-600 dark:text-indigo-400 uppercase tracking-widest block mb-2">Display Font</span>
                    <h5 className="text-xl font-bold text-slate-900 dark:text-white mb-1" style={{ fontFamily: 'var(--font-display)' }}>
                      {kitResult.typography.heading}
                    </h5>
                    <p className="text-[10px] font-mono text-slate-400">Used for titles, headers, and visual hero units</p>
                  </div>

                  {/* Body typography */}
                  <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-950 border border-slate-100 dark:border-slate-850">
                    <span className="text-[10px] font-bold text-indigo-600 dark:text-indigo-400 uppercase tracking-widest block mb-2">Body Font</span>
                    <h5 className="text-base font-normal text-slate-800 dark:text-slate-200 mb-1" style={{ fontFamily: 'var(--font-sans)' }}>
                      {kitResult.typography.body}
                    </h5>
                    <p className="text-[10px] font-mono text-slate-400">Used for long reading segments, paragraphs, and lists</p>
                  </div>

                  {/* Rationale explanation */}
                  <div className="pt-2">
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-2">Pairing Archetype Theory</span>
                    <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
                      {kitResult.typography.rationale}
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* 3. Social Branding Suite (Full Column Width) */}
            <div className="md:col-span-2 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl p-6 sm:p-8 shadow-md space-y-6">
              <div className="flex items-center gap-2 pb-3 border-b border-slate-100 dark:border-slate-800">
                <MessageSquare className="w-5 h-5 text-indigo-500" />
                <h4 className="font-display font-bold text-slate-900 dark:text-white text-base">
                  Social Media Branding Suite & Copywriting
                </h4>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                
                {/* Copyable Bio */}
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">
                      Professional Bio (Copy Ready)
                    </span>
                    <button
                      onClick={() => handleCopyText(kitResult.socialKit.bio, 'bio')}
                      className="p-1.5 hover:bg-slate-50 dark:hover:bg-slate-800 rounded-lg text-slate-400 hover:text-indigo-600 transition cursor-pointer"
                    >
                      {copiedSection === 'bio' ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
                    </button>
                  </div>
                  <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-950 border border-slate-100 dark:border-slate-850 text-sm text-slate-700 dark:text-slate-300 leading-relaxed font-sans">
                    {kitResult.socialKit.bio}
                  </div>
                </div>

                {/* Cover Banner Description */}
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">
                      Creative Banner Prompt Guide
                    </span>
                    <button
                      onClick={() => handleCopyText(kitResult.socialKit.coverPrompt, 'cover')}
                      className="p-1.5 hover:bg-slate-50 dark:hover:bg-slate-800 rounded-lg text-slate-400 hover:text-indigo-600 transition cursor-pointer"
                    >
                      {copiedSection === 'cover' ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
                    </button>
                  </div>
                  <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-950 border border-slate-100 dark:border-slate-850 text-sm text-slate-700 dark:text-slate-300 leading-relaxed italic">
                    "{kitResult.socialKit.coverPrompt}"
                  </div>
                </div>

                {/* Caption guidelines */}
                <div className="md:col-span-2 space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">
                      Social Posting Guidelines & Hashtag Archetypes
                    </span>
                    <button
                      onClick={() => handleCopyText(kitResult.socialKit.postTemplate, 'template')}
                      className="p-1.5 hover:bg-slate-50 dark:hover:bg-slate-800 rounded-lg text-slate-400 hover:text-indigo-600 transition cursor-pointer"
                    >
                      {copiedSection === 'template' ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
                    </button>
                  </div>
                  <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-950 border border-slate-100 dark:border-slate-850 text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
                    {kitResult.socialKit.postTemplate}
                  </div>
                </div>

              </div>
            </div>

          </div>
        </div>
      )}

    </div>
  );
}
