import DomainItem from "./DomainItem";
import React, { useState } from 'react';
import { translations } from '../translations';
import { Language, UserProfile, GeneratedName } from '../types';
import { Sparkles, Copy, Check, Bookmark, Globe, ArrowRight, AlertTriangle, HelpCircle, Share2 } from 'lucide-react';
import { fetchAPI } from '../lib/api';
import LoadingOverlay from './ui/LoadingOverlay';

interface NameGeneratorProps {
  language: Language;
  user: UserProfile | null;
  onDeductCredits: (amount: number) => boolean;
  onSaveName: (name: GeneratedName) => void;
  savedNames: GeneratedName[];
  onOpenLogin: () => void;
}

export default function NameGenerator({
  language,
  user,
  onDeductCredits,
  onSaveName,
  savedNames,
  onOpenLogin,
}: NameGeneratorProps) {
  const t = translations[language];

  const [prompt, setPrompt] = useState('');
  const [industry, setIndustry] = useState('');
  const [country, setCountry] = useState('Global');
  const [style, setStyle] = useState('modern');
  const [brandLang, setBrandLang] = useState(language);
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState<GeneratedName[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    
    if (!user) {
      onOpenLogin();
      return;
    }

    setError(null);
    setLoading(true);

    const userCredits = user && typeof user.credits === 'number' && !isNaN(user.credits) ? user.credits : 0;
    if (userCredits < 2) {
      setError(language === 'en' ? 'Insufficient credits! Please upgrade your plan or purchase credits.' : 'رصيدك غير كافٍ! يرجى ترقية باقتك أو شراء رصيد إضافي.');
      setLoading(false);
      return;
    }

    try {
      const resJson = await fetchAPI('/api/generate-names', {
        method: 'POST',
        body: JSON.stringify({
          prompt,
          industry,
          country,
          style,
          language: brandLang
        })
      });

      if (resJson.success) {
        onDeductCredits(2);
        setResults(resJson.data);
      } else {
        throw new Error(resJson.error || 'Failed to generate names');
      }
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Something went wrong while connecting to the AI Forge. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleShare = async (item: GeneratedName) => {
    const textToShare = `${item.name} - ${brandLang === 'ar' && item.meaningAr ? item.meaningAr : item.meaning}\nGenerated by BrandForge AI`;
    if (navigator.share) {
      try {
        await navigator.share({
          title: item.name,
          text: textToShare,
        });
      } catch (err) {
        console.error('Error sharing:', err);
      }
    } else {
      navigator.clipboard.writeText(textToShare);
      alert(language === 'ar' ? 'تم نسخ النص للمشاركة!' : 'Text copied to clipboard for sharing!');
    }
  };

  const handleCopy = (name: string, index: number) => {
    navigator.clipboard.writeText(name);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const isSaved = (nameStr: string) => {
    return savedNames.some(item => item.name === nameStr);
  };

  return (
    <>
      <LoadingOverlay isLoading={loading} language={language} />
      <div className="space-y-8 animate-fade-in">
      
      {/* Search / Config Card */}
      <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl p-6 sm:p-8 shadow-xl shadow-slate-100/40 dark:shadow-none">
        <div className="flex items-center gap-3 mb-6">
          <div className="bg-indigo-100 dark:bg-indigo-950/50 p-2.5 rounded-2xl text-indigo-600 dark:text-indigo-400">
            <Sparkles className="w-6 h-6 animate-pulse" />
          </div>
          <div>
            <h2 className="text-xl font-display font-bold text-slate-900 dark:text-white">
              {t.nameGen}
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              {language === 'ar' ? 'يولد حوالي 10 أفكار أسماء فريدة مع المعاني ومقترحات النطاقات (يكلف 2 رصيد)' : 'Generates ~10 unique name concepts with meaning and domain suggestions (Costs 2 credits)'}
            </p>
          </div>
        </div>

        {/* Input Prompts */}
        <div className="space-y-6">
          <div>
            <label className="block text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2">
              {language === 'ar' ? 'وصف فكرة المشروع التجاري' : 'Business Concept Description'}
            </label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder={t.promptPlaceholder}
              rows={3}
              className="w-full px-4 py-3 text-sm rounded-2xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 dark:focus:ring-indigo-950/40 focus:outline-none transition-all placeholder:text-slate-400"
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div>
              <label className="block text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2">
                {t.industry}
              </label>
              <input
                type="text"
                value={industry}
                onChange={(e) => setIndustry(e.target.value)}
                placeholder="e.g. AI, Organic Food, Gaming"
                className="w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 focus:border-indigo-500 focus:outline-none transition-all"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2">
                {t.country}
              </label>
              <input
                type="text"
                value={country}
                onChange={(e) => setCountry(e.target.value)}
                placeholder="e.g. Global, KSA, UK"
                className="w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 focus:border-indigo-500 focus:outline-none transition-all"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2">
                {t.style}
              </label>
              <select
                value={style}
                onChange={(e) => setStyle(e.target.value)}
                className="w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 text-slate-700 dark:text-slate-300 focus:border-indigo-500 focus:outline-none transition-all"
              >
                <option value="modern">{t.modernNames}</option>
                <option value="short">{t.shortNames}</option>
                <option value="premium">{t.premiumNames}</option>
                <option value="creative">{t.creativeNames}</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2">
                {t.language}
              </label>
              <select
                value={brandLang}
                onChange={(e) => setBrandLang(e.target.value as Language)}
                className="w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 text-slate-700 dark:text-slate-300 focus:border-indigo-500 focus:outline-none transition-all"
              >
                <option value="en">{t.english}</option>
                <option value="ar">{t.arabic}</option>
              </select>
            </div>
          </div>

          <div className="flex items-center justify-between pt-4 border-t border-slate-100 dark:border-slate-800">
            <div className="flex items-center gap-2 text-xs text-slate-500 dark:text-slate-400">
              <span className="inline-block w-2 h-2 rounded-full bg-amber-500 animate-pulse"></span>
              <span>{language === 'ar' ? 'التكلفة: 2 رصيد' : 'Credits Cost: 2 credits'}</span>
            </div>

            <button
              onClick={handleGenerate}
              disabled={loading || !prompt.trim()}
              className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white font-medium text-sm px-6 py-3 rounded-xl transition duration-150 cursor-pointer shadow-lg shadow-indigo-600/10"
            >
              {loading ? (
                <>
                  <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                  <span>{t.generating}</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  <span>{t.generate}</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* Error Alert */}
      {error && (
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 rounded-2xl bg-rose-50 dark:bg-rose-950/20 border border-rose-100 dark:border-rose-900 text-rose-800 dark:text-rose-400 text-sm">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 flex-shrink-0 mt-0.5" />
            <p>{error}</p>
          </div>
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="flex items-center justify-center gap-1.5 self-start sm:self-center bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 text-white font-medium text-xs px-4 py-2 rounded-xl transition duration-150 cursor-pointer shadow-md shrink-0"
          >
            <span>{language === 'ar' ? 'إعادة المحاولة' : 'Retry'}</span>
          </button>
        </div>
      )}

      {/* Loading Skeletons */}
      {loading && (
        <div className="space-y-6 animate-pulse">
          <div className="flex items-center justify-between">
            <div className="h-6 w-48 bg-slate-200 dark:bg-slate-800 rounded-lg"></div>
            <div className="h-4 w-36 bg-slate-100 dark:bg-slate-850 rounded-lg"></div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {[...Array(4)].map((_, index) => (
              <div
                key={index}
                className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-2xl p-6 relative flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <div className="w-16 h-5 bg-slate-200 dark:bg-slate-800 rounded-lg"></div>
                    <div className="flex items-center gap-2">
                      <div className="w-8 h-8 bg-slate-100 dark:bg-slate-850 rounded-lg"></div>
                      <div className="w-8 h-8 bg-slate-100 dark:bg-slate-850 rounded-lg"></div>
                    </div>
                  </div>

                  <div className="w-40 h-8 bg-slate-200 dark:bg-slate-800 rounded-xl mb-4"></div>
                  
                  <div className="space-y-2 mb-4">
                    <div className="w-full h-4 bg-slate-100 dark:bg-slate-850 rounded-lg"></div>
                    <div className="w-5/6 h-4 bg-slate-100 dark:bg-slate-850 rounded-lg"></div>
                  </div>
                </div>

                <div className="border-t border-slate-100 dark:border-slate-800 pt-4 mt-4">
                  <div className="w-24 h-4 bg-slate-200 dark:bg-slate-800 rounded-lg mb-2"></div>
                  <div className="flex flex-wrap gap-2">
                    <div className="w-16 h-6 bg-slate-100 dark:bg-slate-850 rounded-lg"></div>
                    <div className="w-20 h-6 bg-slate-100 dark:bg-slate-850 rounded-lg"></div>
                    <div className="w-14 h-6 bg-slate-100 dark:bg-slate-850 rounded-lg"></div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Results Section */}
      {results.length > 0 && !loading && (
        <div className="space-y-6">
          <div className="flex items-center justify-between">
            <h3 className="font-display font-semibold text-lg text-slate-800 dark:text-slate-200">
              {language === 'ar' ? 'الأسماء التجارية المصنوعة' : 'Forged Business Names'}
            </h3>
            <span className="text-xs text-slate-400">
              {language === 'ar' ? 'انقر على علامة المرجعية لحفظ الاسم بشكل دائم' : 'Click bookmark to save name permanently'}
            </span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {results.map((item, index) => (
              <div
                key={index}
                className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-2xl p-6 relative hover:shadow-lg hover:shadow-slate-100/50 dark:hover:shadow-none transition-all flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-xs font-semibold px-2.5 py-1 rounded-lg bg-indigo-50 dark:bg-indigo-950/40 text-indigo-700 dark:text-indigo-400">
                      {item.style}
                    </span>
                    
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => handleCopy(item.name, index)}
                        className="p-1.5 hover:bg-slate-50 dark:hover:bg-slate-800 rounded-lg text-slate-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition cursor-pointer"
                        title={t.copy}
                      >
                        {copiedIndex === index ? (
                          <Check className="w-4 h-4 text-emerald-500" />
                        ) : (
                          <Copy className="w-4 h-4" />
                        )}
                      </button>

                      <button
                        onClick={() => onSaveName(item)}
                        className={`p-1.5 rounded-lg transition cursor-pointer ${
                          isSaved(item.name)
                            ? 'text-amber-500 bg-amber-50 dark:bg-amber-950/30'
                            : 'text-slate-400 hover:text-amber-500 hover:bg-slate-50 dark:hover:bg-slate-800'
                        }`}
                        title={t.save}
                      >
                        <Bookmark className="w-4 h-4" />
                      </button>
                    </div>
                  </div>

                  <h4 className="font-display font-bold text-2xl text-indigo-600 dark:text-indigo-400 mb-2">
                    {item.name}
                  </h4>

                  <p className="text-sm text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
                    {brandLang === 'ar' && item.meaningAr ? item.meaningAr : item.meaning}
                  </p>
                </div>

                {/* Domain list */}
                <div className="border-t border-slate-100 dark:border-slate-800 pt-4 mt-4">
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-2 flex items-center gap-1">
                    <Globe className="w-3 h-3 text-emerald-500" />
                    {t.domainCheck}
                  </span>
                  <div className="flex flex-wrap gap-2">
                    {item.domainSuggestions?.map((domain, dIdx) => (
                      <DomainItem key={dIdx} domain={domain} />
                    ))}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

    </div>
    </>
  );
}
