import React, { useState } from 'react';
import { translations } from '../translations';
import { Language, UserProfile, GeneratedSlogan } from '../types';
import { Sparkles, Copy, Check, MessageSquare, AlertTriangle, Share2 } from 'lucide-react';
import { fetchAPI } from '../lib/api';
import LoadingOverlay from './ui/LoadingOverlay';

interface SloganGeneratorProps {
  language: Language;
  user: UserProfile | null;
  onDeductCredits: (amount: number) => boolean;
  onSaveSlogan: (slogan: GeneratedSlogan) => void;
  savedSlogans: GeneratedSlogan[];
  onOpenLogin: () => void;
}

export default function SloganGenerator({
  language,
  user,
  onDeductCredits,
  onSaveSlogan,
  savedSlogans,
  onOpenLogin,
}: SloganGeneratorProps) {
  const t = translations[language];

  const [prompt, setPrompt] = useState('');
  const [length, setLength] = useState('short');
  const [brandLang, setBrandLang] = useState(language);
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState<GeneratedSlogan[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;

    if (!user) {
      onOpenLogin();
      return;
    }

    setError(null);
    setLoading(true);

    const userCredits = user && typeof user.credits === 'number' && !isNaN(user.credits) ? user.credits : 0;
    if (userCredits < 1) {
      setError(language === 'en' ? 'Insufficient credits! Please upgrade your plan or purchase credits.' : 'رصيدك غير كافٍ! يرجى ترقية باقتك أو شراء رصيد إضافي.');
      setLoading(false);
      return;
    }

    try {
      const resJson = await fetchAPI('/api/generate-slogans', {
        method: 'POST',
        body: JSON.stringify({
          prompt,
          length,
          language: brandLang
        })
      });

      if (resJson.success) {
        onDeductCredits(1);
        setResults(resJson.data);
      } else {
        throw new Error(resJson.error || 'Failed to generate slogans');
      }
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Something went wrong. Please check your internet connection and try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleShare = async (item: GeneratedSlogan) => {
    const textToShare = `${item.slogan}\nGenerated by BrandForge AI`;
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Brand Slogan Idea',
          text: textToShare,
        });
      } catch (err) {
        console.error('Error sharing:', err);
      }
    } else {
      navigator.clipboard.writeText(textToShare);
      alert(language === 'ar' ? 'تم نسخ النص للمشاركة!' : 'Text copied to clipboard for sharing!');
    }
  };

  const handleCopy = (text: string, index: number) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  return (
    <>
      <LoadingOverlay isLoading={loading} language={language} />
      <div className="space-y-8 animate-fade-in">
      <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl p-6 sm:p-8 shadow-xl shadow-slate-100/40 dark:shadow-none">
        
        <div className="flex items-center gap-3 mb-6">
          <div className="bg-indigo-100 dark:bg-indigo-950/50 p-2.5 rounded-2xl text-indigo-600 dark:text-indigo-400">
            <MessageSquare className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-display font-bold text-slate-900 dark:text-white">
              {t.sloganGen}
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              {language === 'ar' ? 'يولد 10 عبارات تسويقية أو شعارات مميزة بناءً على قيمك (يكلف 1 رصيد)' : 'Generates 10 premium slogans, mottos, or copy variations based on your values (Costs 1 credit)'}
            </p>
          </div>
        </div>

        {/* Form fields */}
        <div className="space-y-6">
          <div>
            <label className="block text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2">
              {language === 'ar' ? 'ما هي القيم أو الفكرة التي تمثلها علامتك التجارية؟' : 'What does your brand stand for?'}
            </label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder={language === 'ar' ? 'مثال: أحذية رياضية صديقة للبيئة مع وسادة عضوية فائقة النعومة وبصمة كربونية محايدة' : 'e.g. Eco-friendly sneakers with ultra-soft organic cushion and carbon neutral footprints'}
              rows={3}
              className="w-full px-4 py-3 text-sm rounded-2xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 dark:focus:ring-indigo-950/40 focus:outline-none transition-all placeholder:text-slate-400"
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2">
                {t.sloganLength}
              </label>
              <select
                value={length}
                onChange={(e) => setLength(e.target.value)}
                className="w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 text-slate-700 dark:text-slate-300 focus:border-indigo-500 focus:outline-none transition-all"
              >
                <option value="short">{t.short}</option>
                <option value="long">{t.long}</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2">
                {t.language}
              </label>
              <select
                value={brandLang}
                onChange={(e) => setBrandLang(e.target.value as Language)}
                className="w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 text-slate-700 dark:text-slate-300 focus:border-indigo-500 focus:outline-none transition-all"
              >
                <option value="en">{t.english}</option>
                <option value="ar">{t.arabic}</option>
              </select>
            </div>
          </div>

          {/* Deduct block */}
          <div className="flex items-center justify-between pt-4 border-t border-slate-100 dark:border-slate-800">
            <div className="flex items-center gap-2 text-xs text-slate-500 dark:text-slate-400">
              <span className="inline-block w-2 h-2 rounded-full bg-amber-500 animate-pulse"></span>
              <span>{language === 'ar' ? 'التكلفة: 1 رصيد' : 'Credits Cost: 1 credit'}</span>
            </div>

            <button
              onClick={handleGenerate}
              disabled={loading || !prompt.trim()}
              className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white font-medium text-sm px-6 py-3 rounded-xl transition duration-150 cursor-pointer shadow-lg shadow-indigo-600/10"
            >
              {loading ? (
                <>
                  <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                  <span>{t.generating}</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  <span>{t.generate}</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* Error Alert */}
      {error && (
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 rounded-2xl bg-rose-50 dark:bg-rose-950/20 border border-rose-100 dark:border-rose-900 text-rose-800 dark:text-rose-400 text-sm">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 flex-shrink-0 mt-0.5" />
            <p>{error}</p>
          </div>
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="flex items-center justify-center gap-1.5 self-start sm:self-center bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 text-white font-medium text-xs px-4 py-2 rounded-xl transition duration-150 cursor-pointer shadow-md shrink-0"
          >
            <span>{language === 'ar' ? 'إعادة المحاولة' : 'Retry'}</span>
          </button>
        </div>
      )}

      {/* Loading Skeletons */}
      {loading && (
        <div className="space-y-4 animate-pulse">
          <div className="h-6 w-48 bg-slate-200 dark:bg-slate-800 rounded-lg mb-2"></div>

          <div className="grid grid-cols-1 gap-3">
            {[...Array(5)].map((_, index) => (
              <div
                key={index}
                className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-2xl p-5 flex items-center justify-between"
              >
                <div className="space-y-2.5 w-2/3">
                  <div className="w-20 h-4 bg-slate-200 dark:bg-slate-800 rounded-md"></div>
                  <div className="w-full h-5 bg-slate-100 dark:bg-slate-850 rounded-lg"></div>
                </div>

                <div className="flex items-center gap-2">
                  <div className="w-9 h-9 bg-slate-100 dark:bg-slate-850 rounded-xl"></div>
                  <div className="w-9 h-9 bg-slate-100 dark:bg-slate-850 rounded-xl"></div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Results */}
      {results.length > 0 && !loading && (
        <div className="space-y-4">
          <h3 className="font-display font-semibold text-lg text-slate-800 dark:text-slate-200">
            {language === 'ar' ? 'الشعارات التسويقية والعبارات المصنوعة' : 'Forged Taglines & Slogans'}
          </h3>

          <div className="grid grid-cols-1 gap-3">
            {results.map((item, index) => (
              <div
                key={index}
                className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-2xl p-5 flex items-center justify-between hover:shadow-md transition-all group"
              >
                <div className="space-y-1">
                  <span className="text-[10px] uppercase tracking-wider font-bold text-slate-400 px-2 py-0.5 rounded-md bg-slate-50 dark:bg-slate-950 border border-slate-100 dark:border-slate-850">
                    {item.vibe}
                  </span>
                  <p className="text-base font-medium text-slate-800 dark:text-slate-200 pt-1">
                    "{item.slogan}"
                  </p>
                </div>

                <div className="flex items-center gap-2">
                  <button
                    onClick={() => handleCopy(item.slogan, index)}
                    className="p-2 hover:bg-slate-50 dark:hover:bg-slate-850 rounded-xl text-slate-400 hover:text-indigo-600 transition cursor-pointer"
                  >
                    {copiedIndex === index ? (
                      <Check className="w-4 h-4 text-emerald-500" />
                    ) : (
                      <Copy className="w-4 h-4" />
                    )}
                  </button>

                  <button
                    onClick={() => onSaveSlogan(item)}
                    className="p-2 hover:bg-slate-50 dark:hover:bg-slate-850 rounded-xl text-slate-400 hover:text-amber-500 transition cursor-pointer"
                    title={t.save}
                  >
                    <Sparkles className="w-4 h-4" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

    </div>
    </>
  );
}
